id: ICE6FB059
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:19:44.762018+00:00
last_modified: 2022-12-15 07:19:44.762027+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-057-006
  eft-text-version: 1.2.6 2021
  title: Toh_147-The_Teaching_on_the_Great_Compassion_of_the_Tathagata-v1
bases:
  68F6:
    source_metadata: null
    order: 1
    base_file: 68F6.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
